name: Deploy Reports to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Git (required for gitinspector)
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        
    - name: Generate Reports using local GitInspector
      run: |
        # Usar el GitInspector local que ya funciona
        python gitinspector.py SGA_BACKEND --format=html --file-types=** --timeline --responsibilities --metrics > reporte_sga_backend_completo.html
        python gitinspector.py SGA_BACKEND --format=json --file-types=** > reporte_sga_backend_completo.json
        python gitinspector.py SGA_BACKEND --format=text --file-types=** --timeline --responsibilities --metrics > reporte_sga_backend_completo.txt
        
    - name: Create index.html
      run: |
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>SGA GitInspector - Análisis de Métricas</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }
                .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                h1 { color: #2c3e50; text-align: center; margin-bottom: 30px; }
                .report-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin-top: 30px; }
                .report-card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; background: #f9f9f9; }
                .report-card h3 { color: #34495e; margin-top: 0; }
                .report-card p { color: #666; }
                .btn { display: inline-block; padding: 10px 20px; background: #3498db; color: white; text-decoration: none; border-radius: 5px; margin-top: 10px; }
                .btn:hover { background: #2980b9; }
                .info { background: #e8f4fd; border-left: 4px solid #3498db; padding: 15px; margin: 20px 0; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>📊 SGA GitInspector - Análisis de Métricas</h1>
                
                <div class="info">
                    <strong>Repositorio Analizado:</strong> <a href="https://github.com/TALLER-USMP/SGA_BACKEND" target="_blank">TALLER-USMP/SGA_BACKEND</a><br>
                    <strong>Tecnologías:</strong> Node.js, TypeScript, Azure Functions, PostgreSQL, Drizzle ORM<br>
                    <strong>Arquitectura:</strong> Serverless con Controllers y Attribute-Based Routing
                </div>
                
                <div class="report-grid">
                    <div class="report-card">
                        <h3>📈 Reporte HTML Completo</h3>
                        <p>Análisis visual interactivo con todos los commits, timeline de actividad, responsabilidades por autor y métricas de calidad.</p>
                        <a href="reporte_sga_backend_completo.html" class="btn" target="_blank">Ver Reporte HTML</a>
                    </div>
                    
                    <div class="report-card">
                        <h3>📋 Reporte JSON</h3>
                        <p>Datos estructurados en formato JSON para integración con otras herramientas o análisis programático.</p>
                        <a href="reporte_sga_backend_completo.json" class="btn" target="_blank">Ver Reporte JSON</a>
                    </div>
                    
                    <div class="report-card">
                        <h3>📄 Reporte de Texto</h3>
                        <p>Resumen ejecutivo en formato de texto plano con las métricas principales del proyecto.</p>
                        <a href="reporte_sga_backend_completo.txt" class="btn" target="_blank">Ver Reporte Texto</a>
                    </div>
                </div>
                
                <div class="info">
                    <strong>Última actualización:</strong> <span id="fecha"></span><br>
                    <strong>Herramienta:</strong> GitInspector v0.5.0dev<br>
                    <strong>Análisis incluye:</strong> Todos los tipos de archivo (--file-types=**)
                </div>
            </div>
            
            <script>
                document.getElementById('fecha').textContent = new Date().toLocaleDateString('es-ES');
            </script>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
